// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzQlQfkXep3eBqYJmOiZ6hxFvrRwuauc',
    appId: '1:392244476564:web:tennis-club-web-app',
    messagingSenderId: '392244476564',
    projectId: 'myapp1-c6012',
    authDomain: 'myapp1-c6012.firebaseapp.com',
    storageBucket: 'myapp1-c6012.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTzQlQfkXep3eBqYJmOiZ6hxFvrRwuauc',
    appId: '1:392244476564:android:tennis-club-android',
    messagingSenderId: '392244476564',
    projectId: 'myapp1-c6012',
    storageBucket: 'myapp1-c6012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzQlQfkXep3eBqYJmOiZ6hxFvrRwuauc',
    appId: '1:392244476564:ios:5ad77e494add0fa20a9281',
    messagingSenderId: '392244476564',
    projectId: 'myapp1-c6012',
    storageBucket: 'myapp1-c6012.firebasestorage.app',
    iosBundleId: 'com.tennisclub.pickleconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzQlQfkXep3eBqYJmOiZ6hxFvrRwuauc',
    appId: '1:392244476564:ios:5ad77e494add0fa20a9281',
    messagingSenderId: '392244476564',
    projectId: 'myapp1-c6012',
    storageBucket: 'myapp1-c6012.firebasestorage.app',
    iosBundleId: 'com.tennisclub.pickleconnect',
  );
}